version: "3.2"

services:
  dev:
    container_name: dasua
    image: paritytech/ci-linux:production
    working_dir: /var/www/dasua
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/dasua/.cargo
    volumes:
      - .:/var/www/dasua
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/dasua --dev --ws-external"
